/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'price' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'timestamp' : IDL.Int,
  'contactNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Product],
      [],
    ),
  'getAllOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'submitOrder' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [Order],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'price' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'timestamp' : IDL.Int,
    'contactNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Product],
        [],
      ),
    'getAllOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'submitOrder' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [Order],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };